[package]
name = "test-rs"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"]}
